{
    "updated": "2026-08-25",
    "games": [
        {
            "name": "Violence District",
            "status": "green"
        },
        {
            "name": "Blade Ball",
            "status": "green"
        },
        {
            "name": "Kick A Lucky Block",
            "status": "green"
        },
        {
            "name": "Grow A Garden 2",
            "status": "green"
        },
        {
            "name": "Fish It",
            "status": "green"
        },

        {
            "name": "Survive The Apocalypse",
            "status": "yellow"
        },
        {
            "name": "Dueling Ground",
            "status": "yellow"
        },
        {
            "name": "Slime RNG",
            "status": "yellow"
        },
        {
            "name": "Survive Zombie Arena",
            "status": "yellow"
        },
        {
            "name": "Blox Fruits",
            "status": "yellow"
        },
        {
            "name": "Sailor Piece",
            "status": "yellow"
        },

        {
            "name": "Bite By Night",
            "status": "red"
        },
        {
            "name": "Steal A Brainrot",
            "status": "red"
        },
        {
            "name": "FishGo",
            "status": "red"
        }
    ]
}
